### PR TITLE
Assignment done

### PR DESCRIPTION
**Pull request by kris-19**

### CODE REVIEW

**Comment by bhavesh1129** [comment]
@kris-19, I'm closing this pull request because it doesn't meet the assignment's requirement of creating a pull request with your "name.txt" file containing a brief introduction about yourself. Please submit a new pull request that fulfills this requirement.

**Comment by kris-19** [comment]
Its fine @bhavesh1129 . Wouldn't learn anything by doing that anyway.

**Comment by bhavesh1129** [comment]
@kris-19, How? 
You also submitted a PR, but the content is different, and you added multiple files. The goal was to make it easier for students to use Git so that they can regularly push their code.

**Comment by kris-19** [comment]
_"The goal was to make it easier for students to use Git so that they can regularly push their code."_
So don't you think the goal was achieved when I added multiple files and raised a PR ?

In the strict purview of the assignment, I'd agree that my changes were not in line with what was asked  but I don't think that matters remotely in the context of learning git. 

It'd probably come under the context of how you're supposed to do exactly as per Business requirement and BA's Suggestion as part of story/epic development.

Pretty sure "adding only 1 text file with your introduction to learn git" doesn't come in that. 
Does it?

PS: I'm plenty familiar with git.

**Comment by bhavesh1129** [comment]
Of course, I'd like to make it clear that even though I closed your PR with the condition that the requirements must be met, the BA's suggestions and requirements are not relevant here. It's crucial not to overlook these minor details in this context. 

But my goal is to uphold an organized approach, which is why I made this request to all the people. Please take a moment to review the other PRs and their related files. And your expertise with Git is highly valued. 

Thank you.

**Pull request closed without merging**
